name: Deploy Backend to Render

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        run: curl -X POST https://api.render.com/deploy/srv-XXXXXX
