name: Ping Backend to Keep Awake

on:
  schedule:
    - cron: "*/5 * * * *" # Her 5 dakikada bir çalışır
  workflow_dispatch: # Manuel çalıştırma opsiyonu

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend via /api/health
        run: |
          curl -s --fail https://durmusgym.onrender.com/api/health || exit 1
