name: Ping Backend to Keep Awake

on:
  schedule:
    - cron: "*/5 * * * *" # Her 5 dakikada bir çalışacak
  workflow_dispatch: # İstersen manuel de tetikleyebilirsin

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://durmusgym.onrender.com || exit 1
